### ISSUE TITLE
Handle HTTP(S) redirects? 

### ISSUE THREAD

**Issue by rocky** [ConsenSysDiligence/armlet#17]
Should armlet handle these? For example: 

```
 ./analysis 
Error: Invalid status code 308, <html>
<head><title>308 Permanent Redirect</title></head>
<body>
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx/1.15.5</center>
</body>
</html>
```

**Comment by birdofpreyru** [comment]
It happens only if `http://` scheme is used instead of `https://`. For me it seems fine to crush, so that user figures out that he should use `https://` instead, and not to cause any redirects.

**Comment by rocky** [comment]
This is the situation now, but is that always going to be the case?

**Comment by rocky** [comment]
This was addressed along with URL canonicalization in https://github.com/ConsenSys/armlet/pull/53 .
